name: Lint with Vale

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vale-lint:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Vale
    - name: Install Vale
      run: |
        curl -L https://github.com/errata-ai/vale/releases/latest/download/vale_linux_amd64.tar.gz -o vale.tar.gz
        tar -xzf vale.tar.gz
        sudo mv vale /usr/local/bin/
        vale --version

    # Step 3: Run Vale linter
    - name: Run Vale linter
      run: |
        vale .
      continue-on-error: false
